### ISSUE TITLE
Support translation on the skill table view

### ISSUE THREAD

**Issue by hyunsikjeong** [ssdh233/gitadora-skill-viewer#191]
The table header is still not translated yet, fixed to: `曲名 | レベル | 達成率 | スキル`.
(See http://gsv.fun/zh/highvoltage/1/g, http://gsv.fun/en/highvoltage/1/g and http://gsv.fun/ko/highvoltage/1/g. It's the same!)
It would be great if there's support for these.

For Korean, use:
* `曲名`: `곡명`
* `レベル`: `레벨`
* `達成率`: `달성률`
* `スキル`: `스킬`

**Comment by ssdh233** [comment]
Sure, will send an update this weekend.

**Comment by ssdh233** [comment]
Solved by https://github.com/ssdh233/gitadora-skill-viewer/pull/192
