### ISSUE TITLE
cannot open slide toggles when a page was loaded over HTTPS

### ISSUE THREAD

**Issue by juchan1220** [ssdh233/gitadora-skill-viewer#219]
When a page is loaded over HTTPS, jquery.min.js is blocked due to mixed content, and it causes an error on SlideToggle components.

A possible solution is to replace jQuery CDN with a HTTPS link (e.g. https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js) or re-implement SlideToggle component without jQuery.

**Comment by ssdh233** [comment]
Sorry for the late reply. I just saw the message.

Originally I didn't provide https access for gsv.fun on purpose. I'll reconsider it and reply soon

**Comment by ssdh233** [comment]
Fixed at https://github.com/ssdh233/gitadora-skill-viewer/pull/220
